services:
  mariadb:
    image: mariadb:11
    ports:
      - "3308:3306"
    environment:
      MARIADB_ROOT_PASSWORD: KlokkeklangKrissegutt04
      MARIADB_DATABASE: ObstacleDb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - appnet

  firstwebapplication1:
    image: firstwebapplication
    build:
      context: .
      dockerfile: FirstWebApplication1/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=mariadb;port=3306;database=ObstacleDb;user=root;password=KlokkeklangKrissegutt04;TreatTinyAsBoolean=false;ConnectionTimeout=15;DefaultCommandTimeout=30
    depends_on:
      - mariadb
    networks:
      - appnet

volumes:
  mariadb_data:

networks:
  appnet:
    external: true
    name: appnet
